services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - database-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  code-dev:
  database-dev:
